# Generated by Django 5.1 on 2024-08-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0003_alter_testimonial_relationship_to_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
