# Generated by Django 4.2.6 on 2024-08-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0007_alter_testimonial_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
