# Generated by Django 4.2.6 on 2024-08-29 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0009_testimonial_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
