# Generated by Django 5.1 on 2024-08-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100)),
                ('pupil_name', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('toddler_1', 'Toddler 1'), ('toddler_2', 'Toddler 2'), ('junior_infant', 'Junior Infant'), ('senior_infant', 'Senior Infant'), ('year_one', 'Year One'), ('year_two', 'Year Two'), ('year_three', 'Year Three'), ('year_four', 'Year Four'), ('year_five', 'Year Five')], max_length=20)),
                ('age', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
