# Generated by Django 5.1 on 2024-08-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('admitted', 'Admitted')], default='pending', max_length=20),
        ),
    ]
