# Generated by Django 4.2.6 on 2024-08-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_pupil_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('contacted', 'Contacted'), ('awaiting_exam', 'Awaiting Exam'), ('admitted', 'Admitted')], default='processing', max_length=20),
        ),
    ]
